export const MARK_ROOT = "ESbuild";
export const MARK_ROLLUP = "Rollup";
export const ERROR_TRANSFORMING = "SyntaxError: Error transforming";
export const ERROR_FETCH = "FetchError:";
export const ERROR_FILE_NOT_FOUNT = "FileNotFound:";
export const DATA_FRAGMENTS = Symbol("_fragments");
export const DATA_LAYOUT = Symbol("_layout");
export const DATA_PAGE = Symbol("_page");
export const FROM_LAYOUT = Symbol("_fromLayout");
